# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1e77eb09c8f11d8d4d0daf67ac12bd2f3db7a16f9cefe408a8e3b06a3a00cea43d0db05e2101ae62b2e3e0e72ab9f0a667feba9e8e6931d78a6266bfe86afc37

test:
  secret_key_base: 452e5ddb702e5dace283bb6660be0a08293e08613b4ad635f08018933bb6ed941f18db969a02bb586b85efa0ccbeefd12c5f4f19d52d426912d27723b494603f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
